### ISSUE TITLE
Unknown2 in Controllable physics serilization is undocumented

### ISSUE THREAD

**Issue by aronwk-aaron** [lcdr/lu_packets#3]
Unknown 2 in controllable physics serialization is missing/incorrect.

https://github.com/lcdr/lu_packets/blob/master/src/raknet/client/replica/controllable_physics.rs#L42-L45

Here is a partial implementation in DLU with the first parts being pickup radius control used for magnet abilities.

https://github.com/DarkflameUniverse/DarkflameServer/blob/main/dGame/dComponents/ControllablePhysicsComponent.cpp#L92-L97

The second unimplemented part has to do with bubbles from ZP/YRK that were used in skunk invasions

**Comment by lcdr** [comment]
Not sure what you mean, the part with the pickup radius is documented (within Unknown1), the other struct is undocumented in DLU as well.

**Comment by aronwk-aaron** [comment]
My apologies, got confused. unknown2 is bubble stuff
https://github.com/DarkflameUniverse/DarkflameServer/pull/737/files#diff-bc530fb71b3ec1cf8adb09121c58e95987d5863a7849c6defcdf72688fe19d44
here is a partial implementation that Jett did, but wasn't merged into DLU

There are also associated GM's for activating and deactivating the bubble from the server and maybe one for tell the server that the bubble popped on the client
